language: php

sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.1
  - 5.6

before_script:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
