language: php

sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
