language: php

dist: trusty
sudo: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

before_script:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
